name: 'Surgical Deploy: Project 3'

on:
  push:
    branches: [main]
    paths:
      - 'project_3/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-project.yml
    secrets: inherit
    with:
      deployment_name: Build and Deploy Project 3
      project_path: project_3
      service_name: project-3
      dockerfile_path: project_3/Dockerfile
      shared_lib_version_file: project_3/shared_lib_version
      max_instances: "10"
      min_instances: "0"
      memory: 512Mi
      cpu: "1"
